### ISSUE TITLE
Compiler built-ins not resolved

### ISSUE THREAD

**Issue by MarkZ3** [rungemar/cmake4cdt#5]
If I create a Hello world project, standard headers and not resolved (#include <iostream>, etc)

I'm not sure if those include paths are supposed to come from the CMake json output. If not, the relevant language settings provider should be enabled. For example, on Linux using GCC, the "GCC Built-in Compiler Settings" should be enabled by default.

**Comment by rungemar** [comment]
The CMake json output just lists the compiler invocations that the actual build will do. I have to parse them in the same way as the compile output parser does (that's why I want to use it). The same is true for the built-in compiler settings.

As soon as I know, which compiler is used (from the json file available after the CMake run), I want to enable the corresponding built-in compiler settings scanner and the build output parser dynamically.

If it show to be to hard to dynamically do this with the current build model, I intend to use an intermediate solution with fixed default per platform...

**Comment by MarkZ3** [comment]
Ah yes, I had the wrong idea about what the json output was.

For the short term, perhaps it would be good to just enable the base "CDT GCC Built-in Compiler Settings". This should work OK for Linux GCC, MinGW GCC and Mac GCC, as long as gcc is on the PATH.

**Comment by rungemar** [comment]
News: current version will detect c++/g++/gcc, its path and its prefix from compile_command.json file. It then uses a derived version of "CDT GCC Built-in Compiler Settings" to get the built-in settings.
I had to also respect the --sysroot compiler switch. Without it, a cross compiler built with Yocto (not-sysrooted, sysroot is given on the arguments) did not find the mot simple include paths.
